source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.6.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.1'
gem 'puma', '~> 4.3'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'pg'
gem "bootstrap"
gem 'carrierwave', '~> 2.0'
gem "mini_magick"
gem 'trix-rails', require: 'trix'
gem 'kaminari'
gem 'devise'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
group :development do
  gem 'web-console', '>= 3.3.0'
  gem "letter_opener"
end
group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem "toml-rb"
  gem "heroku_hatchet"
  gem "rspec-core"
  gem "rspec-expectations"
  gem "excon"
  gem "parallel_tests"
  gem 'rspec-retry'
  gem "netrc"
  gem "git", github: "hone/ruby-git", branch: "master"
  gem 'json', '~> 2.0.2'
  gem 'ci-queue', github: 'shopify/ci-queue', branch: 'rspec-log-order'
  gem 'redis'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


